# Generated by Django 2.2.11 on 2020-06-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(upload_to='media/')),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
